server:
  port: 8082

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/pet_test?serverTimezone=Asia/Seoul
    username : root
    password: mySql*!$Ms0828

mybatis:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: 'true'
    call-setters-on-nulls: 'false'

logging:
  level:
    jdbc:
      connection: 'OFF'
      sql only: 'OFF'
      result: 'OFF'
      result settable: 'OFF'
      sliding: INFO
      audit: 'OFF'

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  generate-ddl: true
  defer-datasource-initialization: true

